### ISSUE TITLE
Investivate Intel Skylake odd performance

### ISSUE THREAD

**Issue by koichi-murakami** [koichi-murakami/g4bench#47]
https://aloiskraus.wordpress.com/2018/06/16/why-skylakex-cpus-are-sometimes-50-slower-how-intel-has-broken-existing-code/

**Comment by Alois-xx** [comment]
Interesting. I did not know that Geant is still in use. Last time it was 20 years ago during my diploma thesis in Garching. Perhaps you know Oliver Kortner from that time?

**Comment by koichi-murakami** [comment]
AMD Ryzen shows good scalability. Xeon shows bad performance, especially for voxel geometry. It is really messed up!!
